with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDirRelative}}/mocks"
outpkg: "mocks"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/ciphermountain/deadenz/pkg:
    # place your package-specific config here
    config:
    interfaces:
      Loader:
  github.com/ciphermountain/deadenz/pkg/data:
    # place your package-specific config here
    config:
    interfaces:
      # select the interfaces you want mocked
      Loader:
        config:
  github.com/ciphermountain/deadenz/pkg/middleware:
    config:
    interfaces:
      ItemProvider:
      TrapProvider:
      EventPublisher:
