// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLoader is an autogenerated mock type for the Loader type
type MockLoader struct {
	mock.Mock
}

type MockLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoader) EXPECT() *MockLoader_Expecter {
	return &MockLoader_Expecter{mock: &_m.Mock}
}

// Data provides a mock function with given fields: _a0
func (_m *MockLoader) Data(_a0 context.Context) ([]byte, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoader_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type MockLoader_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockLoader_Expecter) Data(_a0 interface{}) *MockLoader_Data_Call {
	return &MockLoader_Data_Call{Call: _e.mock.On("Data", _a0)}
}

func (_c *MockLoader_Data_Call) Run(run func(_a0 context.Context)) *MockLoader_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLoader_Data_Call) Return(_a0 []byte, _a1 error) *MockLoader_Data_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoader_Data_Call) RunAndReturn(run func(context.Context) ([]byte, error)) *MockLoader_Data_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoader creates a new instance of MockLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoader {
	mock := &MockLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
