// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	components "github.com/ciphermountain/deadenz/pkg/components"

	mock "github.com/stretchr/testify/mock"

	opts "github.com/ciphermountain/deadenz/pkg/opts"
)

// MockItemProvider is an autogenerated mock type for the ItemProvider type
type MockItemProvider struct {
	mock.Mock
}

type MockItemProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemProvider) EXPECT() *MockItemProvider_Expecter {
	return &MockItemProvider_Expecter{mock: &_m.Mock}
}

// Item provides a mock function with given fields: _a0, _a1
func (_m *MockItemProvider) Item(_a0 components.ItemType, _a1 ...opts.Option) (*components.Item, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Item")
	}

	var r0 *components.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(components.ItemType, ...opts.Option) (*components.Item, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(components.ItemType, ...opts.Option) *components.Item); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*components.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(components.ItemType, ...opts.Option) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemProvider_Item_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Item'
type MockItemProvider_Item_Call struct {
	*mock.Call
}

// Item is a helper method to define mock.On call
//   - _a0 components.ItemType
//   - _a1 ...opts.Option
func (_e *MockItemProvider_Expecter) Item(_a0 interface{}, _a1 ...interface{}) *MockItemProvider_Item_Call {
	return &MockItemProvider_Item_Call{Call: _e.mock.On("Item",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockItemProvider_Item_Call) Run(run func(_a0 components.ItemType, _a1 ...opts.Option)) *MockItemProvider_Item_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]opts.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(opts.Option)
			}
		}
		run(args[0].(components.ItemType), variadicArgs...)
	})
	return _c
}

func (_c *MockItemProvider_Item_Call) Return(_a0 *components.Item, _a1 error) *MockItemProvider_Item_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemProvider_Item_Call) RunAndReturn(run func(components.ItemType, ...opts.Option) (*components.Item, error)) *MockItemProvider_Item_Call {
	_c.Call.Return(run)
	return _c
}

// Items provides a mock function with given fields: _a0
func (_m *MockItemProvider) Items(_a0 ...opts.Option) ([]components.Item, error) {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Items")
	}

	var r0 []components.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(...opts.Option) ([]components.Item, error)); ok {
		return rf(_a0...)
	}
	if rf, ok := ret.Get(0).(func(...opts.Option) []components.Item); ok {
		r0 = rf(_a0...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]components.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(...opts.Option) error); ok {
		r1 = rf(_a0...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemProvider_Items_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Items'
type MockItemProvider_Items_Call struct {
	*mock.Call
}

// Items is a helper method to define mock.On call
//   - _a0 ...opts.Option
func (_e *MockItemProvider_Expecter) Items(_a0 ...interface{}) *MockItemProvider_Items_Call {
	return &MockItemProvider_Items_Call{Call: _e.mock.On("Items",
		append([]interface{}{}, _a0...)...)}
}

func (_c *MockItemProvider_Items_Call) Run(run func(_a0 ...opts.Option)) *MockItemProvider_Items_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]opts.Option, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(opts.Option)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockItemProvider_Items_Call) Return(_a0 []components.Item, _a1 error) *MockItemProvider_Items_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemProvider_Items_Call) RunAndReturn(run func(...opts.Option) ([]components.Item, error)) *MockItemProvider_Items_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemProvider creates a new instance of MockItemProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemProvider {
	mock := &MockItemProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
