// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishGameEvent provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockEventPublisher) PublishGameEvent(_a0 context.Context, _a1 string, _a2 []byte) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for PublishGameEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishGameEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishGameEvent'
type MockEventPublisher_PublishGameEvent_Call struct {
	*mock.Call
}

// PublishGameEvent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 []byte
func (_e *MockEventPublisher_Expecter) PublishGameEvent(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockEventPublisher_PublishGameEvent_Call {
	return &MockEventPublisher_PublishGameEvent_Call{Call: _e.mock.On("PublishGameEvent", _a0, _a1, _a2)}
}

func (_c *MockEventPublisher_PublishGameEvent_Call) Run(run func(_a0 context.Context, _a1 string, _a2 []byte)) *MockEventPublisher_PublishGameEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockEventPublisher_PublishGameEvent_Call) Return(_a0 error) *MockEventPublisher_PublishGameEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishGameEvent_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockEventPublisher_PublishGameEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
