// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: pkg/proto/core/core.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	// option allow_alias = true;
	Status_OK      Status = 0
	Status_Failure Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "Failure",
	}
	Status_value = map[string]int32{
		"OK":      0,
		"Failure": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_core_core_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pkg_proto_core_core_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{0}
}

type AssetType int32

const (
	AssetType_ItemAsset         AssetType = 0
	AssetType_CharacterAsset    AssetType = 1
	AssetType_ItemDecisionAsset AssetType = 2
	AssetType_ActionAsset       AssetType = 3
	AssetType_LiveMutationAsset AssetType = 4
	AssetType_DieMutationAsset  AssetType = 5
	AssetType_EncounterAsset    AssetType = 6
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ItemAsset",
		1: "CharacterAsset",
		2: "ItemDecisionAsset",
		3: "ActionAsset",
		4: "LiveMutationAsset",
		5: "DieMutationAsset",
		6: "EncounterAsset",
	}
	AssetType_value = map[string]int32{
		"ItemAsset":         0,
		"CharacterAsset":    1,
		"ItemDecisionAsset": 2,
		"ActionAsset":       3,
		"LiveMutationAsset": 4,
		"DieMutationAsset":  5,
		"EncounterAsset":    6,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_core_core_proto_enumTypes[1].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_pkg_proto_core_core_proto_enumTypes[1]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{1}
}

type RunRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	// Types that are assignable to Command:
	//
	//	*RunRequest_Walk
	//	*RunRequest_Spawnin
	Command isRunRequest_Command `protobuf_oneof:"command"`
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (m *RunRequest) GetCommand() isRunRequest_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *RunRequest) GetWalk() *WalkCommand {
	if x, ok := x.GetCommand().(*RunRequest_Walk); ok {
		return x.Walk
	}
	return nil
}

func (x *RunRequest) GetSpawnin() *SpawninCommand {
	if x, ok := x.GetCommand().(*RunRequest_Spawnin); ok {
		return x.Spawnin
	}
	return nil
}

type isRunRequest_Command interface {
	isRunRequest_Command()
}

type RunRequest_Walk struct {
	Walk *WalkCommand `protobuf:"bytes,2,opt,name=walk,proto3,oneof"`
}

type RunRequest_Spawnin struct {
	Spawnin *SpawninCommand `protobuf:"bytes,3,opt,name=spawnin,proto3,oneof"`
}

func (*RunRequest_Walk) isRunRequest_Command() {}

func (*RunRequest_Spawnin) isRunRequest_Command() {}

type WalkCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WalkCommand) Reset() {
	*x = WalkCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalkCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkCommand) ProtoMessage() {}

func (x *WalkCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkCommand.ProtoReflect.Descriptor instead.
func (*WalkCommand) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{1}
}

type SpawninCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpawninCommand) Reset() {
	*x = SpawninCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawninCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawninCommand) ProtoMessage() {}

func (x *SpawninCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawninCommand.ProtoReflect.Descriptor instead.
func (*SpawninCommand) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{2}
}

type LoadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type AssetType `protobuf:"varint,1,opt,name=type,proto3,enum=core.AssetType" json:"type,omitempty"`
	// Types that are assignable to Loader:
	//
	//	*LoadRequest_FileLoader
	//	*LoadRequest_SqlLoader
	Loader isLoadRequest_Loader `protobuf_oneof:"loader"`
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{3}
}

func (x *LoadRequest) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ItemAsset
}

func (m *LoadRequest) GetLoader() isLoadRequest_Loader {
	if m != nil {
		return m.Loader
	}
	return nil
}

func (x *LoadRequest) GetFileLoader() *FileLoader {
	if x, ok := x.GetLoader().(*LoadRequest_FileLoader); ok {
		return x.FileLoader
	}
	return nil
}

func (x *LoadRequest) GetSqlLoader() *SQLLoader {
	if x, ok := x.GetLoader().(*LoadRequest_SqlLoader); ok {
		return x.SqlLoader
	}
	return nil
}

type isLoadRequest_Loader interface {
	isLoadRequest_Loader()
}

type LoadRequest_FileLoader struct {
	FileLoader *FileLoader `protobuf:"bytes,2,opt,name=fileLoader,proto3,oneof"`
}

type LoadRequest_SqlLoader struct {
	SqlLoader *SQLLoader `protobuf:"bytes,3,opt,name=sqlLoader,proto3,oneof"`
}

func (*LoadRequest_FileLoader) isLoadRequest_Loader() {}

func (*LoadRequest_SqlLoader) isLoadRequest_Loader() {}

type FileLoader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *FileLoader) Reset() {
	*x = FileLoader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileLoader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLoader) ProtoMessage() {}

func (x *FileLoader) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLoader.ProtoReflect.Descriptor instead.
func (*FileLoader) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{4}
}

func (x *FileLoader) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SQLLoader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dsn string `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
}

func (x *SQLLoader) Reset() {
	*x = SQLLoader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQLLoader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLLoader) ProtoMessage() {}

func (x *SQLLoader) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLLoader.ProtoReflect.Descriptor instead.
func (*SQLLoader) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{5}
}

func (x *SQLLoader) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

type AssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type AssetType `protobuf:"varint,1,opt,name=type,proto3,enum=core.AssetType" json:"type,omitempty"`
}

func (x *AssetRequest) Reset() {
	*x = AssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetRequest) ProtoMessage() {}

func (x *AssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetRequest.ProtoReflect.Descriptor instead.
func (*AssetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{6}
}

func (x *AssetRequest) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ItemAsset
}

type RunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Profile  *Profile  `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Events   []string  `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{7}
}

func (x *RunResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RunResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *RunResponse) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  Status `protobuf:"varint,1,opt,name=status,proto3,enum=core.Status" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{8}
}

func (x *Response) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid          string     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Xp            uint64     `protobuf:"varint,2,opt,name=xp,proto3" json:"xp,omitempty"`
	Currency      uint64     `protobuf:"varint,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Active        *Character `protobuf:"bytes,4,opt,name=active,proto3,oneof" json:"active,omitempty"`
	ActiveItem    *uint64    `protobuf:"varint,5,opt,name=activeItem,proto3,oneof" json:"activeItem,omitempty"`
	BackpackLimit uint32     `protobuf:"varint,6,opt,name=backpackLimit,proto3" json:"backpackLimit,omitempty"`
	Backpack      []uint64   `protobuf:"varint,7,rep,packed,name=backpack,proto3" json:"backpack,omitempty"`
	Stats         *Stats     `protobuf:"bytes,8,opt,name=stats,proto3" json:"stats,omitempty"`
	Limits        *Limits    `protobuf:"bytes,9,opt,name=limits,proto3,oneof" json:"limits,omitempty"`
}

func (x *Profile) Reset() {
	*x = Profile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{9}
}

func (x *Profile) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Profile) GetXp() uint64 {
	if x != nil {
		return x.Xp
	}
	return 0
}

func (x *Profile) GetCurrency() uint64 {
	if x != nil {
		return x.Currency
	}
	return 0
}

func (x *Profile) GetActive() *Character {
	if x != nil {
		return x.Active
	}
	return nil
}

func (x *Profile) GetActiveItem() uint64 {
	if x != nil && x.ActiveItem != nil {
		return *x.ActiveItem
	}
	return 0
}

func (x *Profile) GetBackpackLimit() uint32 {
	if x != nil {
		return x.BackpackLimit
	}
	return 0
}

func (x *Profile) GetBackpack() []uint64 {
	if x != nil {
		return x.Backpack
	}
	return nil
}

func (x *Profile) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Profile) GetLimits() *Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type uint64 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{10}
}

func (x *Item) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Character struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       uint64 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Multiplier uint32 `protobuf:"varint,3,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
}

func (x *Character) Reset() {
	*x = Character{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{11}
}

func (x *Character) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetMultiplier() uint32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

type Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wit   int32 `protobuf:"varint,1,opt,name=wit,proto3" json:"wit,omitempty"`
	Skill int32 `protobuf:"varint,2,opt,name=skill,proto3" json:"skill,omitempty"`
	Humor int32 `protobuf:"varint,3,opt,name=humor,proto3" json:"humor,omitempty"`
}

func (x *Stats) Reset() {
	*x = Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{12}
}

func (x *Stats) GetWit() int32 {
	if x != nil {
		return x.Wit
	}
	return 0
}

func (x *Stats) GetSkill() int32 {
	if x != nil {
		return x.Skill
	}
	return 0
}

func (x *Stats) GetHumor() int32 {
	if x != nil {
		return x.Humor
	}
	return 0
}

type Limits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastWalk  int64  `protobuf:"varint,1,opt,name=lastWalk,proto3" json:"lastWalk,omitempty"`
	WalkCount string `protobuf:"bytes,2,opt,name=walkCount,proto3" json:"walkCount,omitempty"`
}

func (x *Limits) Reset() {
	*x = Limits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{13}
}

func (x *Limits) GetLastWalk() int64 {
	if x != nil {
		return x.LastWalk
	}
	return 0
}

func (x *Limits) GetWalkCount() string {
	if x != nil {
		return x.WalkCount
	}
	return ""
}

type AssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	// Types that are assignable to Asset:
	//
	//	*AssetResponse_Item
	//	*AssetResponse_Character
	Asset isAssetResponse_Asset `protobuf_oneof:"asset"`
}

func (x *AssetResponse) Reset() {
	*x = AssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetResponse) ProtoMessage() {}

func (x *AssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetResponse.ProtoReflect.Descriptor instead.
func (*AssetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{14}
}

func (x *AssetResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (m *AssetResponse) GetAsset() isAssetResponse_Asset {
	if m != nil {
		return m.Asset
	}
	return nil
}

func (x *AssetResponse) GetItem() *ItemAssetResponse {
	if x, ok := x.GetAsset().(*AssetResponse_Item); ok {
		return x.Item
	}
	return nil
}

func (x *AssetResponse) GetCharacter() *CharacterAssetResponse {
	if x, ok := x.GetAsset().(*AssetResponse_Character); ok {
		return x.Character
	}
	return nil
}

type isAssetResponse_Asset interface {
	isAssetResponse_Asset()
}

type AssetResponse_Item struct {
	Item *ItemAssetResponse `protobuf:"bytes,2,opt,name=item,proto3,oneof"`
}

type AssetResponse_Character struct {
	Character *CharacterAssetResponse `protobuf:"bytes,3,opt,name=character,proto3,oneof"`
}

func (*AssetResponse_Item) isAssetResponse_Asset() {}

func (*AssetResponse_Character) isAssetResponse_Asset() {}

type ItemAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ItemAssetResponse) Reset() {
	*x = ItemAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAssetResponse) ProtoMessage() {}

func (x *ItemAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAssetResponse.ProtoReflect.Descriptor instead.
func (*ItemAssetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{15}
}

func (x *ItemAssetResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CharacterAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Characters []*Character `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
}

func (x *CharacterAssetResponse) Reset() {
	*x = CharacterAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_core_core_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterAssetResponse) ProtoMessage() {}

func (x *CharacterAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_core_core_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterAssetResponse.ProtoReflect.Descriptor instead.
func (*CharacterAssetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_core_core_proto_rawDescGZIP(), []int{16}
}

func (x *CharacterAssetResponse) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

var File_pkg_proto_core_core_proto protoreflect.FileDescriptor

var file_pkg_proto_core_core_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x72,
	0x65, 0x22, 0x9b, 0x01, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x27, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x77, 0x61, 0x6c,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x57,
	0x61, 0x6c, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x04, 0x77, 0x61,
	0x6c, 0x6b, 0x12, 0x30, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x69, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e,
	0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x07, 0x73, 0x70, 0x61,
	0x77, 0x6e, 0x69, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22,
	0x0d, 0x0a, 0x0b, 0x57, 0x61, 0x6c, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x10,
	0x0a, 0x0e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x22, 0xa1, 0x01, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x66,
	0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x09, 0x73, 0x71, 0x6c,
	0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x53, 0x51, 0x4c, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x09, 0x73, 0x71, 0x6c, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x72, 0x22, 0x20, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x1d, 0x0a, 0x09, 0x53, 0x51, 0x4c, 0x4c, 0x6f, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x73, 0x6e, 0x22, 0x33, 0x0a, 0x0c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x7a, 0x0a, 0x0b, 0x52, 0x75,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x4a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0xd1, 0x02, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x78, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x2c,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x48, 0x01, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x88, 0x01,
	0x01, 0x12, 0x24, 0x0a, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x70, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x70, 0x61,
	0x63, 0x6b, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x70,
	0x61, 0x63, 0x6b, 0x18, 0x07, 0x20, 0x03, 0x28, 0x04, 0x52, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x70,
	0x61, 0x63, 0x6b, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x73, 0x48, 0x02, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x88, 0x01,
	0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x42, 0x0d, 0x0a, 0x0b,
	0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x22, 0x2e, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x53, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x77, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x68, 0x75, 0x6d, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x68, 0x75, 0x6d,
	0x6f, 0x72, 0x22, 0x42, 0x0a, 0x06, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x57, 0x61, 0x6c, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x57, 0x61, 0x6c, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x61, 0x6c, 0x6b,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77, 0x61, 0x6c,
	0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xb1, 0x01, 0x0a, 0x0d, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04, 0x69,
	0x74, 0x65, 0x6d, 0x12, 0x3c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x42, 0x07, 0x0a, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x22, 0x35, 0x0a, 0x11, 0x49, 0x74,
	0x65, 0x6d, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x20, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x49, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x52, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x2a, 0x1d, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10, 0x01, 0x2a, 0x97, 0x01, 0x0a, 0x09,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x74, 0x65,
	0x6d, 0x41, 0x73, 0x73, 0x65, 0x74, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11,
	0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x69, 0x76, 0x65, 0x4d, 0x75, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x44,
	0x69, 0x65, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x10,
	0x05, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x10, 0x06, 0x32, 0x99, 0x01, 0x0a, 0x07, 0x44, 0x65, 0x61, 0x64, 0x65, 0x6e,
	0x7a, 0x12, 0x2c, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x2b, 0x0a, 0x04, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x11, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x06,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x12, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x2f, 0x64,
	0x65, 0x61, 0x64, 0x65, 0x6e, 0x7a, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_core_core_proto_rawDescOnce sync.Once
	file_pkg_proto_core_core_proto_rawDescData = file_pkg_proto_core_core_proto_rawDesc
)

func file_pkg_proto_core_core_proto_rawDescGZIP() []byte {
	file_pkg_proto_core_core_proto_rawDescOnce.Do(func() {
		file_pkg_proto_core_core_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_core_core_proto_rawDescData)
	})
	return file_pkg_proto_core_core_proto_rawDescData
}

var file_pkg_proto_core_core_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_proto_core_core_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_proto_core_core_proto_goTypes = []interface{}{
	(Status)(0),                    // 0: core.Status
	(AssetType)(0),                 // 1: core.AssetType
	(*RunRequest)(nil),             // 2: core.RunRequest
	(*WalkCommand)(nil),            // 3: core.WalkCommand
	(*SpawninCommand)(nil),         // 4: core.SpawninCommand
	(*LoadRequest)(nil),            // 5: core.LoadRequest
	(*FileLoader)(nil),             // 6: core.FileLoader
	(*SQLLoader)(nil),              // 7: core.SQLLoader
	(*AssetRequest)(nil),           // 8: core.AssetRequest
	(*RunResponse)(nil),            // 9: core.RunResponse
	(*Response)(nil),               // 10: core.Response
	(*Profile)(nil),                // 11: core.Profile
	(*Item)(nil),                   // 12: core.Item
	(*Character)(nil),              // 13: core.Character
	(*Stats)(nil),                  // 14: core.Stats
	(*Limits)(nil),                 // 15: core.Limits
	(*AssetResponse)(nil),          // 16: core.AssetResponse
	(*ItemAssetResponse)(nil),      // 17: core.ItemAssetResponse
	(*CharacterAssetResponse)(nil), // 18: core.CharacterAssetResponse
}
var file_pkg_proto_core_core_proto_depIdxs = []int32{
	11, // 0: core.RunRequest.profile:type_name -> core.Profile
	3,  // 1: core.RunRequest.walk:type_name -> core.WalkCommand
	4,  // 2: core.RunRequest.spawnin:type_name -> core.SpawninCommand
	1,  // 3: core.LoadRequest.type:type_name -> core.AssetType
	6,  // 4: core.LoadRequest.fileLoader:type_name -> core.FileLoader
	7,  // 5: core.LoadRequest.sqlLoader:type_name -> core.SQLLoader
	1,  // 6: core.AssetRequest.type:type_name -> core.AssetType
	10, // 7: core.RunResponse.response:type_name -> core.Response
	11, // 8: core.RunResponse.profile:type_name -> core.Profile
	0,  // 9: core.Response.status:type_name -> core.Status
	13, // 10: core.Profile.active:type_name -> core.Character
	14, // 11: core.Profile.stats:type_name -> core.Stats
	15, // 12: core.Profile.limits:type_name -> core.Limits
	10, // 13: core.AssetResponse.response:type_name -> core.Response
	17, // 14: core.AssetResponse.item:type_name -> core.ItemAssetResponse
	18, // 15: core.AssetResponse.character:type_name -> core.CharacterAssetResponse
	12, // 16: core.ItemAssetResponse.items:type_name -> core.Item
	13, // 17: core.CharacterAssetResponse.characters:type_name -> core.Character
	2,  // 18: core.Deadenz.Run:input_type -> core.RunRequest
	5,  // 19: core.Deadenz.Load:input_type -> core.LoadRequest
	8,  // 20: core.Deadenz.Assets:input_type -> core.AssetRequest
	9,  // 21: core.Deadenz.Run:output_type -> core.RunResponse
	10, // 22: core.Deadenz.Load:output_type -> core.Response
	16, // 23: core.Deadenz.Assets:output_type -> core.AssetResponse
	21, // [21:24] is the sub-list for method output_type
	18, // [18:21] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pkg_proto_core_core_proto_init() }
func file_pkg_proto_core_core_proto_init() {
	if File_pkg_proto_core_core_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_core_core_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalkCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawninCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileLoader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQLLoader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Character); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Limits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_core_core_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_core_core_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RunRequest_Walk)(nil),
		(*RunRequest_Spawnin)(nil),
	}
	file_pkg_proto_core_core_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*LoadRequest_FileLoader)(nil),
		(*LoadRequest_SqlLoader)(nil),
	}
	file_pkg_proto_core_core_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_pkg_proto_core_core_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*AssetResponse_Item)(nil),
		(*AssetResponse_Character)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_core_core_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_core_core_proto_goTypes,
		DependencyIndexes: file_pkg_proto_core_core_proto_depIdxs,
		EnumInfos:         file_pkg_proto_core_core_proto_enumTypes,
		MessageInfos:      file_pkg_proto_core_core_proto_msgTypes,
	}.Build()
	File_pkg_proto_core_core_proto = out.File
	file_pkg_proto_core_core_proto_rawDesc = nil
	file_pkg_proto_core_core_proto_goTypes = nil
	file_pkg_proto_core_core_proto_depIdxs = nil
}
