// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	opts "github.com/ciphermountain/deadenz/pkg/opts"
)

// MockLoader is an autogenerated mock type for the Loader type
type MockLoader struct {
	mock.Mock
}

type MockLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoader) EXPECT() *MockLoader_Expecter {
	return &MockLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: _a0, _a1
func (_m *MockLoader) Load(_a0 interface{}, _a1 ...opts.Option) error {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...opts.Option) error); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - _a0 interface{}
//   - _a1 ...opts.Option
func (_e *MockLoader_Expecter) Load(_a0 interface{}, _a1 ...interface{}) *MockLoader_Load_Call {
	return &MockLoader_Load_Call{Call: _e.mock.On("Load",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockLoader_Load_Call) Run(run func(_a0 interface{}, _a1 ...opts.Option)) *MockLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]opts.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(opts.Option)
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MockLoader_Load_Call) Return(_a0 error) *MockLoader_Load_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoader_Load_Call) RunAndReturn(run func(interface{}, ...opts.Option) error) *MockLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}

// LoadCtx provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockLoader) LoadCtx(_a0 context.Context, _a1 interface{}, _a2 ...opts.Option) error {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LoadCtx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...opts.Option) error); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoader_LoadCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadCtx'
type MockLoader_LoadCtx_Call struct {
	*mock.Call
}

// LoadCtx is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 interface{}
//   - _a2 ...opts.Option
func (_e *MockLoader_Expecter) LoadCtx(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockLoader_LoadCtx_Call {
	return &MockLoader_LoadCtx_Call{Call: _e.mock.On("LoadCtx",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockLoader_LoadCtx_Call) Run(run func(_a0 context.Context, _a1 interface{}, _a2 ...opts.Option)) *MockLoader_LoadCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]opts.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(opts.Option)
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MockLoader_LoadCtx_Call) Return(_a0 error) *MockLoader_LoadCtx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoader_LoadCtx_Call) RunAndReturn(run func(context.Context, interface{}, ...opts.Option) error) *MockLoader_LoadCtx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoader creates a new instance of MockLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoader {
	mock := &MockLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
